[package]
name = "easy_solana"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.3"
dotenv = "0.15.0"
log = "0.4.22"
solana-client = "2.1.0"
solana-program = "2.1.0"
solana-sdk = "2.1.0"
spl-token = "7.0.0"
thiserror = "2.0.3"
