name: Rust

on: [push]

env:
  RPC_URL: ${{secrets.RPC_URL}}
  PRIVATE_KEY_1: ${{secrets.PRIVATE_KEY_1}}
  PRIVATE_KEY_2: ${{secrets.PRIVATE_KEY_2}}
  CARGO_TERM_COLOR: always

jobs:
  build:
    environment: Easy Solana Env
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
