name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env: 
        RPC_URL: ${{ secrets.RPC_URL }}
      run: cargo test --verbose
